/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PrivatecreatorRouteRouteImport } from './routes/_privatecreator/route'
import { Route as PubliccreatorRouteRouteImport } from './routes/_publiccreator/route'
import { Route as PrivatecreatorDashboardRouteImport } from './routes/_privatecreator/dashboard'
import { Route as PrivatecreatorLeaderboardRouteImport } from './routes/_privatecreator/leaderboard'
import { Route as PrivatecreatorNotificationsRouteImport } from './routes/_privatecreator/notifications'
import { Route as PrivatecreatorOpportunitiesRouteImport } from './routes/_privatecreator/opportunities'
import { Route as PrivatecreatorProfileRouteImport } from './routes/_privatecreator/profile'
import { Route as PrivatecreatorRewardsRouteImport } from './routes/_privatecreator/rewards'
import { Route as PrivatecreatorSubmissionsRouteImport } from './routes/_privatecreator/submissions'
import { Route as PubliccreatorLoginRouteImport } from './routes/_publiccreator/login'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSignInRouteImport } from './routes/admin/sign-in'
import { Route as PrivatecreatorIdeasIndexRouteImport } from './routes/_privatecreator/ideas.index'
import { Route as PrivatecreatorIdeasNewRouteImport } from './routes/_privatecreator/ideas.new'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminAdminsRouteImport } from './routes/admin/_admin/admins'
import { Route as AdminAdminApplicantsRouteImport } from './routes/admin/_admin/applicants'
import { Route as AdminAdminAuditLogRouteImport } from './routes/admin/_admin/audit-log'
import { Route as AdminAdminCategoriesRouteImport } from './routes/admin/_admin/categories'
import { Route as AdminAdminContentReviewRouteImport } from './routes/admin/_admin/content-review'
import { Route as AdminAdminLeaderboardRouteImport } from './routes/admin/_admin/leaderboard'
import { Route as AdminAdminNotificationsRouteImport } from './routes/admin/_admin/notifications'
import { Route as AdminAdminPayoutsRouteImport } from './routes/admin/_admin/payouts'
import { Route as AdminAdminProfileRouteImport } from './routes/admin/_admin/profile'
import { Route as AdminAdminReportsRouteImport } from './routes/admin/_admin/reports'
import { Route as AdminAdminRewardsRouteImport } from './routes/admin/_admin/rewards'
import { Route as AdminAdminTopicsRouteImport } from './routes/admin/_admin/topics'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatecreatorRouteRoute = PrivatecreatorRouteRouteImport.update({
  id: '/_privatecreator',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliccreatorRouteRoute = PubliccreatorRouteRouteImport.update({
  id: '/_publiccreator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatecreatorDashboardRoute = PrivatecreatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivatecreatorRouteRoute,
} as any)
const PrivatecreatorLeaderboardRoute =
  PrivatecreatorLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => PrivatecreatorRouteRoute,
  } as any)
const PrivatecreatorNotificationsRoute =
  PrivatecreatorNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PrivatecreatorRouteRoute,
  } as any)
const PrivatecreatorOpportunitiesRoute =
  PrivatecreatorOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => PrivatecreatorRouteRoute,
  } as any)
const PrivatecreatorProfileRoute = PrivatecreatorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivatecreatorRouteRoute,
} as any)
const PrivatecreatorRewardsRoute = PrivatecreatorRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => PrivatecreatorRouteRoute,
} as any)
const PrivatecreatorSubmissionsRoute =
  PrivatecreatorSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => PrivatecreatorRouteRoute,
  } as any)
const PubliccreatorLoginRoute = PubliccreatorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PubliccreatorRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/admin/sign-in',
  path: '/admin/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatecreatorIdeasIndexRoute =
  PrivatecreatorIdeasIndexRouteImport.update({
    id: '/ideas/',
    path: '/ideas/',
    getParentRoute: () => PrivatecreatorRouteRoute,
  } as any)
const PrivatecreatorIdeasNewRoute = PrivatecreatorIdeasNewRouteImport.update({
  id: '/ideas/new',
  path: '/ideas/new',
  getParentRoute: () => PrivatecreatorRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAdminsRoute = AdminAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminApplicantsRoute = AdminAdminApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditLogRoute = AdminAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminContentReviewRoute = AdminAdminContentReviewRouteImport.update({
  id: '/content-review',
  path: '/content-review',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLeaderboardRoute = AdminAdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPayoutsRoute = AdminAdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProfileRoute = AdminAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRewardsRoute = AdminAdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTopicsRoute = AdminAdminTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PubliccreatorRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/dashboard': typeof PrivatecreatorDashboardRoute
  '/leaderboard': typeof PrivatecreatorLeaderboardRoute
  '/notifications': typeof PrivatecreatorNotificationsRoute
  '/opportunities': typeof PrivatecreatorOpportunitiesRoute
  '/profile': typeof PrivatecreatorProfileRoute
  '/rewards': typeof PrivatecreatorRewardsRoute
  '/submissions': typeof PrivatecreatorSubmissionsRoute
  '/login': typeof PubliccreatorLoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/ideas/new': typeof PrivatecreatorIdeasNewRoute
  '/admin/admins': typeof AdminAdminAdminsRoute
  '/admin/applicants': typeof AdminAdminApplicantsRoute
  '/admin/audit-log': typeof AdminAdminAuditLogRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/content-review': typeof AdminAdminContentReviewRoute
  '/admin/leaderboard': typeof AdminAdminLeaderboardRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/payouts': typeof AdminAdminPayoutsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/rewards': typeof AdminAdminRewardsRoute
  '/admin/topics': typeof AdminAdminTopicsRoute
  '/ideas/': typeof PrivatecreatorIdeasIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PubliccreatorRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/dashboard': typeof PrivatecreatorDashboardRoute
  '/leaderboard': typeof PrivatecreatorLeaderboardRoute
  '/notifications': typeof PrivatecreatorNotificationsRoute
  '/opportunities': typeof PrivatecreatorOpportunitiesRoute
  '/profile': typeof PrivatecreatorProfileRoute
  '/rewards': typeof PrivatecreatorRewardsRoute
  '/submissions': typeof PrivatecreatorSubmissionsRoute
  '/login': typeof PubliccreatorLoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/ideas/new': typeof PrivatecreatorIdeasNewRoute
  '/admin/admins': typeof AdminAdminAdminsRoute
  '/admin/applicants': typeof AdminAdminApplicantsRoute
  '/admin/audit-log': typeof AdminAdminAuditLogRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/content-review': typeof AdminAdminContentReviewRoute
  '/admin/leaderboard': typeof AdminAdminLeaderboardRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/payouts': typeof AdminAdminPayoutsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/rewards': typeof AdminAdminRewardsRoute
  '/admin/topics': typeof AdminAdminTopicsRoute
  '/ideas': typeof PrivatecreatorIdeasIndexRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_privatecreator': typeof PrivatecreatorRouteRouteWithChildren
  '/_publiccreator': typeof PubliccreatorRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_privatecreator/dashboard': typeof PrivatecreatorDashboardRoute
  '/_privatecreator/leaderboard': typeof PrivatecreatorLeaderboardRoute
  '/_privatecreator/notifications': typeof PrivatecreatorNotificationsRoute
  '/_privatecreator/opportunities': typeof PrivatecreatorOpportunitiesRoute
  '/_privatecreator/profile': typeof PrivatecreatorProfileRoute
  '/_privatecreator/rewards': typeof PrivatecreatorRewardsRoute
  '/_privatecreator/submissions': typeof PrivatecreatorSubmissionsRoute
  '/_publiccreator/login': typeof PubliccreatorLoginRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/_privatecreator/ideas/new': typeof PrivatecreatorIdeasNewRoute
  '/admin/_admin/admins': typeof AdminAdminAdminsRoute
  '/admin/_admin/applicants': typeof AdminAdminApplicantsRoute
  '/admin/_admin/audit-log': typeof AdminAdminAuditLogRoute
  '/admin/_admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/_admin/content-review': typeof AdminAdminContentReviewRoute
  '/admin/_admin/leaderboard': typeof AdminAdminLeaderboardRoute
  '/admin/_admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/_admin/payouts': typeof AdminAdminPayoutsRoute
  '/admin/_admin/profile': typeof AdminAdminProfileRoute
  '/admin/_admin/reports': typeof AdminAdminReportsRoute
  '/admin/_admin/rewards': typeof AdminAdminRewardsRoute
  '/admin/_admin/topics': typeof AdminAdminTopicsRoute
  '/_privatecreator/ideas/': typeof PrivatecreatorIdeasIndexRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/leaderboard'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/rewards'
    | '/submissions'
    | '/login'
    | '/admin'
    | '/admin/login'
    | '/admin/sign-in'
    | '/ideas/new'
    | '/admin/admins'
    | '/admin/applicants'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/content-review'
    | '/admin/leaderboard'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/topics'
    | '/ideas/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/leaderboard'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/rewards'
    | '/submissions'
    | '/login'
    | '/admin/login'
    | '/admin/sign-in'
    | '/ideas/new'
    | '/admin/admins'
    | '/admin/applicants'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/content-review'
    | '/admin/leaderboard'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/topics'
    | '/ideas'
    | '/admin'
  id:
    | '__root__'
    | '/_privatecreator'
    | '/_publiccreator'
    | '/$'
    | '/_privatecreator/dashboard'
    | '/_privatecreator/leaderboard'
    | '/_privatecreator/notifications'
    | '/_privatecreator/opportunities'
    | '/_privatecreator/profile'
    | '/_privatecreator/rewards'
    | '/_privatecreator/submissions'
    | '/_publiccreator/login'
    | '/admin/_admin'
    | '/admin/login'
    | '/admin/sign-in'
    | '/_privatecreator/ideas/new'
    | '/admin/_admin/admins'
    | '/admin/_admin/applicants'
    | '/admin/_admin/audit-log'
    | '/admin/_admin/categories'
    | '/admin/_admin/content-review'
    | '/admin/_admin/leaderboard'
    | '/admin/_admin/notifications'
    | '/admin/_admin/payouts'
    | '/admin/_admin/profile'
    | '/admin/_admin/reports'
    | '/admin/_admin/rewards'
    | '/admin/_admin/topics'
    | '/_privatecreator/ideas/'
    | '/admin/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivatecreatorRouteRoute: typeof PrivatecreatorRouteRouteWithChildren
  PubliccreatorRouteRoute: typeof PubliccreatorRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignInRoute: typeof AdminSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privatecreator': {
      id: '/_privatecreator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivatecreatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publiccreator': {
      id: '/_publiccreator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PubliccreatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privatecreator/dashboard': {
      id: '/_privatecreator/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivatecreatorDashboardRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/leaderboard': {
      id: '/_privatecreator/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof PrivatecreatorLeaderboardRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/notifications': {
      id: '/_privatecreator/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof PrivatecreatorNotificationsRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/opportunities': {
      id: '/_privatecreator/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof PrivatecreatorOpportunitiesRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/profile': {
      id: '/_privatecreator/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivatecreatorProfileRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/rewards': {
      id: '/_privatecreator/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof PrivatecreatorRewardsRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/submissions': {
      id: '/_privatecreator/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof PrivatecreatorSubmissionsRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_publiccreator/login': {
      id: '/_publiccreator/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PubliccreatorLoginRouteImport
      parentRoute: typeof PubliccreatorRouteRoute
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/admin/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privatecreator/ideas/': {
      id: '/_privatecreator/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof PrivatecreatorIdeasIndexRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/_privatecreator/ideas/new': {
      id: '/_privatecreator/ideas/new'
      path: '/ideas/new'
      fullPath: '/ideas/new'
      preLoaderRoute: typeof PrivatecreatorIdeasNewRouteImport
      parentRoute: typeof PrivatecreatorRouteRoute
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/admins': {
      id: '/admin/_admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminAdminsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/applicants': {
      id: '/admin/_admin/applicants'
      path: '/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminAdminApplicantsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/audit-log': {
      id: '/admin/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAdminAuditLogRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/categories': {
      id: '/admin/_admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/content-review': {
      id: '/admin/_admin/content-review'
      path: '/content-review'
      fullPath: '/admin/content-review'
      preLoaderRoute: typeof AdminAdminContentReviewRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/leaderboard': {
      id: '/admin/_admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminAdminLeaderboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/notifications': {
      id: '/admin/_admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/payouts': {
      id: '/admin/_admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminAdminPayoutsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/profile': {
      id: '/admin/_admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAdminProfileRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/reports': {
      id: '/admin/_admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/rewards': {
      id: '/admin/_admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminAdminRewardsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/topics': {
      id: '/admin/_admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminAdminTopicsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface PrivatecreatorRouteRouteChildren {
  PrivatecreatorDashboardRoute: typeof PrivatecreatorDashboardRoute
  PrivatecreatorLeaderboardRoute: typeof PrivatecreatorLeaderboardRoute
  PrivatecreatorNotificationsRoute: typeof PrivatecreatorNotificationsRoute
  PrivatecreatorOpportunitiesRoute: typeof PrivatecreatorOpportunitiesRoute
  PrivatecreatorProfileRoute: typeof PrivatecreatorProfileRoute
  PrivatecreatorRewardsRoute: typeof PrivatecreatorRewardsRoute
  PrivatecreatorSubmissionsRoute: typeof PrivatecreatorSubmissionsRoute
  PrivatecreatorIdeasNewRoute: typeof PrivatecreatorIdeasNewRoute
  PrivatecreatorIdeasIndexRoute: typeof PrivatecreatorIdeasIndexRoute
}

const PrivatecreatorRouteRouteChildren: PrivatecreatorRouteRouteChildren = {
  PrivatecreatorDashboardRoute: PrivatecreatorDashboardRoute,
  PrivatecreatorLeaderboardRoute: PrivatecreatorLeaderboardRoute,
  PrivatecreatorNotificationsRoute: PrivatecreatorNotificationsRoute,
  PrivatecreatorOpportunitiesRoute: PrivatecreatorOpportunitiesRoute,
  PrivatecreatorProfileRoute: PrivatecreatorProfileRoute,
  PrivatecreatorRewardsRoute: PrivatecreatorRewardsRoute,
  PrivatecreatorSubmissionsRoute: PrivatecreatorSubmissionsRoute,
  PrivatecreatorIdeasNewRoute: PrivatecreatorIdeasNewRoute,
  PrivatecreatorIdeasIndexRoute: PrivatecreatorIdeasIndexRoute,
}

const PrivatecreatorRouteRouteWithChildren =
  PrivatecreatorRouteRoute._addFileChildren(PrivatecreatorRouteRouteChildren)

interface PubliccreatorRouteRouteChildren {
  PubliccreatorLoginRoute: typeof PubliccreatorLoginRoute
}

const PubliccreatorRouteRouteChildren: PubliccreatorRouteRouteChildren = {
  PubliccreatorLoginRoute: PubliccreatorLoginRoute,
}

const PubliccreatorRouteRouteWithChildren =
  PubliccreatorRouteRoute._addFileChildren(PubliccreatorRouteRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminAdminsRoute: typeof AdminAdminAdminsRoute
  AdminAdminApplicantsRoute: typeof AdminAdminApplicantsRoute
  AdminAdminAuditLogRoute: typeof AdminAdminAuditLogRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminContentReviewRoute: typeof AdminAdminContentReviewRoute
  AdminAdminLeaderboardRoute: typeof AdminAdminLeaderboardRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminPayoutsRoute: typeof AdminAdminPayoutsRoute
  AdminAdminProfileRoute: typeof AdminAdminProfileRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminRewardsRoute: typeof AdminAdminRewardsRoute
  AdminAdminTopicsRoute: typeof AdminAdminTopicsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAdminsRoute: AdminAdminAdminsRoute,
  AdminAdminApplicantsRoute: AdminAdminApplicantsRoute,
  AdminAdminAuditLogRoute: AdminAdminAuditLogRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminContentReviewRoute: AdminAdminContentReviewRoute,
  AdminAdminLeaderboardRoute: AdminAdminLeaderboardRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminPayoutsRoute: AdminAdminPayoutsRoute,
  AdminAdminProfileRoute: AdminAdminProfileRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminRewardsRoute: AdminAdminRewardsRoute,
  AdminAdminTopicsRoute: AdminAdminTopicsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivatecreatorRouteRoute: PrivatecreatorRouteRouteWithChildren,
  PubliccreatorRouteRoute: PubliccreatorRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignInRoute: AdminSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
